default:
  models:
    AppCollaborator: read
    AppVersion: read
    AppFile: read
    AppGeneration: read
    App: manage
    AppTable: manage
    AppTableColumn: manage
    AppChatMessage: manage
    AppApiCall: manage
    Follow: read
    CreatorProfile: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    AppCollaborator: manage
    AppVersion: manage
    AppFile: manage
    AppGeneration: manage
    App: manage
    AppTable: manage
    AppTableColumn: manage
    AppChatMessage: manage
    AppApiCall: manage
    Follow: manage
    CreatorProfile: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
