development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
  channel_prefix: overskill_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: overskill_production
  driver: :ruby
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
