# Redis configuration for AI context caching
development:
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>
  
test:
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/2' %>
  
production:
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>