:concurrency: 10
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - critical
  - ai_generation
  - ai_naming
  - ai_processing
  - tools
  - deployment
  - preview_updates
  - default
  - mailers
  - low
  - action_mailbox_routing
