:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - critical
  - ai_generation
  - deployment
  - preview_updates
  - default
  - mailers
  - low
  - action_mailbox_routing
